# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

  memcached:
    class: Memcached
    calls:
      - [addServers, [%memcache_servers%]]
      - [setOption, [-1002, '%memcache_prefix%']]

  doctrine.cache.memcached:
    class: Doctrine\Common\Cache\MemcachedCache
    calls:
      - [setMemcached, ['@memcached']]

  skyeng.auth.cache.memcached:
    class: Doctrine\Common\Cache\MemcachedCache
    calls:
      - [setMemcached, ['@memcached']]
      - [setNamespace, ['auth']]

  # makes classes in src/SkyengMainBundle available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  SkyengMainBundle\:
    resource: '../../src/SkyengMainBundle/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../src/SkyengMainBundle/{Entity,Repository,Tests}'

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
#  SkyengMainBundle\Controller\:
#    resource: '../../src/SkyengMainBundle/Controller'
#    autowire: true
#    public: true
#    tags: ['controller.service_arguments']
#
#  SkyengMainBundle\Manager\:
#    resource: '../../src/SkyengMainBundle/Manager/*'
#    autowire: true
#    lazy: true
